name: Build QuickJS WASM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bellard/quickjs

      - uses: mymindstorm/setup-emsdk@v13
        with:
          version: 3.1.64

      - name: Build with Make
        run: |
          make clean
          make qjs.wasm

      - uses: actions/upload-artifact@v4
        with:
          name: quickjs-wasm
          path: |
            qjs.js
            qjs.wasm
