name: Build WASM

on:
  workflow_dispatch:

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mymindstorm/setup-emsdk@v13
        with:
          version: 3.1.64

      - name: Download + Generate Unicode
        run: |
          wget https://raw.githubusercontent.com/bellard/quickjs/master/unicode_download.sh
          wget https://raw.githubusercontent.com/bellard/quickjs/master/unicode_gen.c
          wget https://raw.githubusercontent.com/bellard/quickjs/master/unicode_gen_def.h
          wget https://raw.githubusercontent.com/bellard/quickjs/master/cutils.h
          wget https://raw.githubusercontent.com/bellard/quickjs/master/cutils.c
          bash unicode_download.sh
          gcc unicode_gen.c cutils.c -o unicode_gen
          ./unicode_gen unicode

      - name: Build WASM only
        run: bash release.sh quickjs

      - uses: actions/upload-artifact@v4
        with:
          name: quickjs-wasm
          path: |
            - qjs.js
            - qjs.wasm
