name: Download Web Tree-sitter

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-24.04
    steps:
      - name: Download web-tree-sitter
        run: |
          curl -L https://github.com/tree-sitter/tree-sitter/releases/latest/download/web-tree-sitter.tar.gz -o web.tar.gz
          tar -xzf web.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-core-wasm
          path: 
            tree-sitter.wasm
            tree-sitter.js
